#ifndef CACATUIDAE_INPUT_EMOUSEINPUT_H
#define CACATUIDAE_INPUT_EMOUSEINPUT_H

namespace cac 
{
    enum class EMouseInput 
    {
	LEFT_BUTTON_PRESS,
	LEFT_BUTTON_HOLD,
	LEFT_BUTTON_RELEASE,
	RIGHT_BUTTON_PRESS,
	RIGHT_BUTTON_HOLD,
	RIGHT_BUTTON_RELEASE,
	MOVE,
	NONE
    };
}
#endif